- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Run macOS role"
      include_role:
        name: mac_os
      when: ansible_facts['os_family'] == "Darwin"

    - name: "Run Ubuntu role"
      include_role:
        name: ubuntu
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: "Run Windows role"
      include_role:
        name: windows
      when: ansible_facts['os_family'] == "Windows"
