- name: Install oh-my-zsh
  homebrew:
    name: zsh
    state: present

- name: Install oh-my-zsh plugins
  homebrew:
    name: 
      zsh-completions,
      zsh-autosuggestions,
      zsh-syntax-highlighting,
      fzf,
      zoxide
    state: present

