- name: Install Homebrew Packages
  homebrew:
    name:
      - btop
      - cmake
      - docker
      - ffmpeg
      - fish
      - fzf
      - go
      - mas
      - neovim
      - pandoc
      - rust
      - uv
      - yt-dlp
      - zoxide
    state: present

- name: Install casks
  community.general.homebrew_cask:
    name:
      - bitwarden
      - cyberduck
      - discord
      - firefox
      - font-jetbrains-mono-nerd-font
      - ghostty
      - handbrake
      - keka
      - lulu
      - obsidian
      - private-internet-access
      - vlc
      - visual-studio-code
      - wireshark
    state: present

- name: Install Xcode Command Line Tools
  ansible.builtin.command:
    cmd: xcode-select --install
  args:
    creates: /Library/Developer/CommandLineTools
  register: xcode_install_output

- name: Open the Mac App Store
  ansible.builtin.command:
    cmd: open -a "App Store"
  ignore_errors: true
  register: app_store_open

- name: Confirm App Store login
  pause:
    prompt: |
      Please log in to the Mac App Store manually.
      Press 'Enter' once you are logged in.

- name: Install App Store Apps
  community.general.mas:
    id:
      - 288419283 # RadarScope
    state: present