- name: Install oh-my-zsh
  homebrew:
    name: zsh
    state: present

- name: Get the path to zsh
  ansible.builtin.shell: "which zsh"
  register: zsh_path

- name: Change default shell to zsh for the current user
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
  become: true
  when: zsh_path.stdout != ""

# - name: Clone Oh My Zsh repository to the user's home directory
#   ansible.builtin.git:
#     repo: https://github.com/ohmyzsh/ohmyzsh.git
#     dest: "/Users/{{ ansible_user_id }}/.oh-my-zsh"

# - name: Run Oh My Zsh install script as the current user
#   ansible.builtin.command: "sh /Users/{{ ansible_user_id }}/.oh-my-zsh/tools/install.sh --unattended"

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install oh-my-zsh plugins
  homebrew:
    name: 
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - fzf
      - zoxide
    state: present

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  loop:
    - .zshrc
    - .p10k.zsh
