- name: Install Homebrew Packages
  homebrew:
    name:
      - btop
      - cmake
      - ffmpeg
      - fzf
      - neovim
      - nushell
      - pandoc
      - uv
      - yt-dlp
      - zoxide
    state: present

- name: Install casks
  community.general.homebrew_cask:
    name:
      - cyberduck
      - firefox
      - handbrake
      - keka
    state: present