- name: Set up shell with iTerm2, zsh, p10k, and other tools
  hosts: localhost
  become: true
  block:
    - name: Install iTerm2
      homebrew_cask:
        name: iterm2
        state: present

    - name: Install Hack Nerd Font
      homebrew_cask:
        name: font-hack-nerd-font
        state: present

    - name: Install zoxide
      homebrew:
        name: zoxide
        state: present

    - name: Install fzf (fuzzy finder)
      homebrew:
        name: fzf
        state: present

    - name: Copy iTerm2 preferences
      copy:
        src: "{{ playbook_dir }}/dotfiles/com.googlecode.iterm2.plist"
        dest: ~/Library/Preferences/com.googlecode.iterm2.plist
        mode: '0644'

    - name: Install Oh My Zsh and Powerlevel10k
      ansible.builtin.include_role:
        name: tomereli.oh_my_zsh_p10k
      vars:
        users:
          - username: "{{ ansible_user_id }}"
        zshrc_src_template: "{{ playbook_dir }}/dotfiles/.zshrc"
        p10k_src_file: "{{ playbook_dir }}/dotfiles/.p10k.zsh"
