- name: Install Homebrew Packages
  homebrew:
    name:
      - btop
      - cmake
      - ffmpeg
      - fzf
      - neovim
      - nushell
      - pandoc
      - starship
      - uv
      - yt-dlp
      - zoxide
    state: present

- name: Install casks
  community.general.homebrew_cask:
    name:
      - bitwarden
      - cyberduck
      - firefox
      - font-jetbrains-mono-nerd-font
      - handbrake
      - iterm2
      - keka
      - visual-studio-code
    state: present

- name: Install Xcode Command Line Tools
  ansible.builtin.command:
    cmd: xcode-select --install
  args:
    creates: /Library/Developer/CommandLineTools
  register: xcode_install_output