- name: Install Chocolatey packages
  loop:
    - firefox
    - kb2999226
    - 7zip
    - git
    - vlc
    - vscode
    - powershell-core
    - wireshark
    - ninja
    - wiztree
    # - greenshot # removed because it is currently failing
    - gsudo
    - cmake
    - bat
    - less
    - llvm
    - pandoc
    - visualstudio2022professional
    - uv
    - epicgameslauncher
    - obsidian
    - powertoys
    - zoxide
    - fzf
    - oh-my-posh
    - poshgit
    - tree
  ansible.builtin.win_chocolatey:
    name: "{{ item }}"
    state: present
    params: "-y --verbose"
  loop_control:
    label: "{{ item }}"
  register: choco_results

- name: Install PowerShell Modules
  loop:
    - PowerShellGet -Force -AllowClobber
    - Microsoft.PowerShell.PSResourceGet -Repository PSGallery
    - PSReadLine
  ansible.windows.win_shell: |
    Install-Module {{ item }}
  args:
    executable: pwsh.exe
  loop_control:
    label: "{{ item }}"
  register: ps_modules_results

- name: Ensure PowerShell profile directory exists
  ansible.builtin.win_file:
    path: "C:\\Users\\{{ ansible_env.USERNAME }}\\Documents\\PowerShell"
    state: directory

- name: Copy PowerShell profile to user directory
  ansible.builtin.win_copy:
    src: "dotfiles/Microsoft.PowerShell_profile.ps1"
    dest: "C:\\Users\\{{ ansible_env.USERNAME }}\\Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1"
    force: yes

- name: Generate templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "655"
  loop:
    - src: templates/.gitconfig
      dest: "C:\\Users\\{{ ansible_env.USERNAME }}\\.gitconfig"